server:
  port: 9002
eureka:
  instance:
    hostname: domain-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/