server:
  port: 9002
eureka:
  instance:
    hostname: domain-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.3.32:3306/luyue?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&rewriteBatchedStatements=true
    name:
    username: root
    password: Pangolin123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: debug