server:
  port: 9001
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.3.2:1521:xe
    username: faxin
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true